---
# tasks file for snowflake

- include_tasks: debian-bullseye.yml
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'bullseye'

- include_tasks: debian-bookworm.yml
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'bookworm'

- include_tasks: ubuntu.yml
  when:
   - ansible_distribution == 'Ubuntu'
   - ansible_distribution_release == 'focal' or ansible_distribution_release == 'jammy'

- include_tasks: freebsd.yml
  when:
   - ansible_distribution == 'FreeBSD'

- include_tasks: arch.yml
  when:
   - ansible_distribution == 'Archlinux'

- include_tasks: fedora.yml
  when: ansible_os_family == 'RedHat'
